export {default as Home} from "./home/home"
export {default as Login} from "./login/login"
export {default as Error} from "./error/error"
export {default as Dashboard} from "./dashboard/dashboard"
export {default as Mentors} from "./Mentors/mentors"
